import "oaidl.idl";
import "ocidl.idl";
import "inspectable.idl";

namespace NetUX
{
    [uuid("484F1C82-049E-41D8-983B-3B28BCD50F43")]
    [version(1)]
    interface INetUXCtrl : IInspectable
    {
        HRESULT Show();
    }

    [version(1)]
    [activatable(1)]
    runtimeclass NetUXCtrl
    {
        [default] interface INetUXCtrl;
    }
}
